# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8]
    steps:
      - name: "Cache Maven Repos"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up JDK ${{ matrix.java }}"
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: x64

      - name: "Print maven version"
        run: mvn -version

      - name: "Build with Maven"
        run: mvn clean package -Dmaven.test.skip=true
  
  Docker:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          java: [8]
      steps:
      - name: "Login to Docker Registry"
        uses: docker/login-action@v2
        with:
          registry: release.daocloud.io
          username: ${{ secrets.DAOCLOUD_REGISTRY_USERNAME }}
          password: ${{ secrets.DAOCLOUD_REGISTRY_PWD }}
    
      - name: Get Hash
        id: hash
        run: echo "${{ github.sha }}"

      - name: "Build and Push"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: release.daocloud.io/skoala/envoy-authz-java:${{ github.sha }}
